In [1]:
import pandas as pd

working_path = '/Users/jsha/gjai/nlp/21_practice/'
data_path = '/Users/jsha/gjai/nlp/pytest/data/eng-kor/'
file_name = 'eng-kor_small.txt'

data = pd.read_csv(data_path+file_name, names=['source','target'],
                  sep='\t', encoding='utf-8')

print('data length:', len(data))
print('data type:', type(data))
print('data shape:', data.shape)
print('data sample:\n', data.sample(5))

data length: 1000
data type: <class 'pandas.core.frame.DataFrame'>
data shape: (1000, 2)
data sample:
                 source      target
735  I lost my wallet.  지갑을 잃어버렸어.
485      We succeeded.   우리는 성공했어.
506     I feel lonely.        외로워.
462      Tom chuckled.  톰이 싱긋 웃었어.
539     Stop laughing.      그만 웃어.


In [2]:
print('data.target length:', len(data.target))
print('data.target type:', type(data.target))
print('data.target shape:', data.target.shape)
print('data.target length:', data.target.sample(5))

data.target length: 1000
data.target type: <class 'pandas.core.series.Series'>
data.target shape: (1000,)
data.target length: 413                이해해.
352         톰이 속임수를 썼어.
897    너는 내 것을 가질 수 있다.
516       나는 그를 죽일 것이다.
685             그거 연필이야
Name: target, dtype: object


In [3]:
data.target_input = data.target.apply(lambda x: '\t'+x+'\n')
data.target_output = data.target.apply(lambda x: x+'\n')
print('\ndata.target_input:\n', data.target_input)
print('\ndata.target_output:\n', data.target_output)


data.target_input:
 0                 \t가.\n
1                \t안녕.\n
2                \t뛰어!\n
3                \t뛰어.\n
4                \t누구?\n
             ...        
995     \t노래하는 거 좋아해요?\n
996      \t노래하는 거 좋아해?\n
997    \t고양이를 좋아하지 않아?\n
998      \t꿈은 이루어질 거야.\n
999     \t모두 그녀를 사랑한다.\n
Name: target, Length: 1000, dtype: object

data.target_output:
 0                 가.\n
1                안녕.\n
2                뛰어!\n
3                뛰어.\n
4                누구?\n
            ...       
995     노래하는 거 좋아해요?\n
996      노래하는 거 좋아해?\n
997    고양이를 좋아하지 않아?\n
998      꿈은 이루어질 거야.\n
999     모두 그녀를 사랑한다.\n
Name: target, Length: 1000, dtype: object


/Users/jsha/opt/anaconda3/envs/nlp3710/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.
/Users/jsha/opt/anaconda3/envs/nlp3710/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  


In [4]:
print('data.target_input length:', len(data.target_input))
print('data.target_input type:', type(data.target_input))
print('data.target_input shape:', data.target_input.shape)
print('data.target_input sampe:\n', data.target_input.sample(5))

data.target_input length: 1000
data.target_input type: <class 'pandas.core.series.Series'>
data.target_input shape: (1000,)
data.target_input sampe:
 118         \t집에 와.\n
131        \t손대지 마.\n
74         \t톰을 잡아.\n
887    \t톰은 피를 토했다.\n
764       \t그거 연필이야\n
Name: target, dtype: object


In [5]:
max_src_len = data.source.apply(lambda x: len(x)).max()
print('source sentence max length: ', max_src_len)

max_tar_len = data.target_input.apply(lambda x: len(x)).max() - 2
print('target sentence max length: ', max_tar_len)

source sentence max length:  20
target sentence max length:  19


In [6]:
from keras.preprocessing.text import Tokenizer

tokenizer_source = Tokenizer(num_words=None, char_level=True,
                            lower=False)
tokenizer_source.fit_on_texts(data.source)
word_index_source = tokenizer_source.word_index

print('\n전체에서 %s개의 고유한 토큰을 찾았습니다.' %len(word_index_source))
print('word_index_source: ', word_index_source)

Using TensorFlow backend.



전체에서 64개의 고유한 토큰을 찾았습니다.
word_index_source:  {' ': 1, 'e': 2, 'o': 3, '.': 4, 'a': 5, 't': 6, 'i': 7, 's': 8, 'n': 9, 'r': 10, 'l': 11, 'd': 12, 'm': 13, 'h': 14, 'y': 15, 'u': 16, 'T': 17, 'g': 18, 'I': 19, 'c': 20, 'p': 21, 'w': 22, 'k': 23, "'": 24, 'v': 25, 'b': 26, 'f': 27, '?': 28, 'S': 29, '!': 30, 'W': 31, 'H': 32, 'C': 33, 'D': 34, 'E': 35, 'K': 36, 'A': 37, 'G': 38, 'Y': 39, 'N': 40, 'x': 41, 'F': 42, 'B': 43, 'L': 44, 'M': 45, 'q': 46, ',': 47, 'P': 48, 'R': 49, 'O': 50, 'z': 51, 'J': 52, 'j': 53, 'Q': 54, '-': 55, '7': 56, ':': 57, '4': 58, '5': 59, 'U': 60, '2': 61, '0': 62, '1': 63, '3': 64}


In [7]:
tokenizer_target = Tokenizer(num_words=None, char_level=True,
                            lower=False)
tokenizer_target.fit_on_texts(data.target_input)
word_index_target = tokenizer_target.word_index

print('\n전체에서 %s개의 고유한 토큰을 찾았습니다.' %len(word_index_target))
print('word_index_source: ', word_index_target)


전체에서 558개의 고유한 토큰을 찾았습니다.
word_index_source:  {' ': 1, '\t': 2, '\n': 3, '.': 4, '어': 5, '이': 6, '톰': 7, '해': 8, '아': 9, '은': 10, '다': 11, '그': 12, '가': 13, '는': 14, '?': 15, '나': 16, '거': 17, '!': 18, '고': 19, '하': 20, '을': 21, '했': 22, '요': 23, '있': 24, '야': 25, '지': 26, '었': 27, '사': 28, '난': 29, '말': 30, '들': 31, '기': 32, '게': 33, '리': 34, '를': 35, '니': 36, '도': 37, '우': 38, '좋': 39, '와': 40, '내': 41, '에': 42, '람': 43, '무': 44, '자': 45, '마': 46, '서': 47, '봐': 48, '한': 49, '계': 50, '안': 51, '네': 52, '시': 53, '속': 54, '너': 55, '수': 56, '모': 57, '만': 58, '짓': 59, '라': 60, '두': 61, '누': 62, '일': 63, '세': 64, '정': 65, '웃': 66, '로': 67, '않': 68, '줘': 69, '았': 70, '제': 71, '렸': 72, '걸': 73, '없': 74, '려': 75, '물': 76, '미': 77, '저': 78, '여': 79, '건': 80, '죽': 81, '으': 82, '워': 83, '조': 84, '주': 85, '린': 86, '신': 87, '것': 88, '의': 89, '져': 90, '심': 91, '좀': 92, '운': 93, '인': 94, '구': 95, '진': 96, '렇': 97, '날': 98, '입': 99, '래': 100, '울': 101, '전': 102, '빨': 103, '피': 104, '히': 105, '할': 106

In [8]:
encoder_input = tokenizer_source.texts_to_sequences(data.source)

print('\nResult of encoder_input sequencing: ')
print(data.source[0], encoder_input[0])
print(data.source[1], encoder_input[1])
print(data.source[2], encoder_input[2])
print(data.source[3], encoder_input[3])


Result of encoder_input sequencing: 
Go. [38, 3, 4]
Hi. [32, 7, 4]
Run! [49, 16, 9, 30]
Run. [49, 16, 9, 4]


In [9]:
for num in encoder_input[0]:
    for key, value in word_index_source.items():
        if num == value:
            print(key, end='')

Go.

In [10]:
decoder_input = tokenizer_target.texts_to_sequences(data.target_input)
decoder_output = tokenizer_target.texts_to_sequences(data.target_output)

print('\nResult of decoder_input sequencing: ')
print(data.target_input[0], decoder_input[0])
print(data.target_input[1], decoder_input[1])
print(data.target_input[2], decoder_input[2])

print('\nResult of decoder_target sequencing: ')
print(data.target_output[0], decoder_output[0])
print(data.target_output[1], decoder_output[1])
print(data.target_output[2], decoder_output[2])



Result of decoder_input sequencing: 
	가.
 [2, 13, 4, 3]
	안녕.
 [2, 51, 223, 4, 3]
	뛰어!
 [2, 272, 5, 18, 3]

Result of decoder_target sequencing: 
가.
 [13, 4, 3]
안녕.
 [51, 223, 4, 3]
뛰어!
 [272, 5, 18, 3]


In [11]:
print('data.source type:', type(data.source))
print('encoder_input type:', type(encoder_input))

# print('data.source:\n', data.source)
# print('encoder_input:\n', encoder_input)

data.source type: <class 'pandas.core.series.Series'>
encoder_input type: <class 'list'>


In [12]:
from keras.preprocessing.sequence import pad_sequences

encoder_input = pad_sequences(encoder_input, maxlen=max_src_len,
                             padding='post')
decoder_input = pad_sequences(decoder_input, maxlen=max_tar_len,
                             padding='post')
decoder_output = pad_sequences(decoder_output, maxlen=max_tar_len,
                              padding='post')

print('\nPadding result sample: ')
print(data.target_input[0], decoder_input[0])


Padding result sample: 
	가.
 [ 2 13  4  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]


### padding = "post"로 하는 이유 2가지.
1. 무의미하게 만들어진 패딩을 처음부터 처리할 필요가 없으므로.
2. 훈련일때는 문제가 아니지만, predict 때 새로운 문장이 들어왔을 때는 문제가 된다. 이전 스텝의 결과가 다음 스텝의 input으로 들어가기 때문에(teaching force) padding이 문장 앞에 있으면, 다음 스텝에 전달하는 문자나 단어가 0이 되므로 문장 생성이 제대로 이어지기 어렵다.

In [13]:
print('decoder_input length:', len(decoder_input))
print('decoder_input type:', type(decoder_input))
print('decoder_input shape:', decoder_input.shape)

decoder_input length: 1000
decoder_input type: <class 'numpy.ndarray'>
decoder_input shape: (1000, 19)


# 음절 단위라 워드 임베딩을 하지 않는다.
- 그래서 to_categorical을 이용해서 3D로 만든다.
- 워드임베딩을 못쓰니까 차선책으로.
- 결국 원핫 인코딩을 통해 2D에서 3D로 만든다.

In [14]:
from tensorflow.keras.utils import to_categorical

encoder_input = to_categorical(encoder_input, num_classes=len(word_index_source)+1)
decoder_input = to_categorical(decoder_input, num_classes=len(word_index_target)+1)
decoder_output = to_categorical(decoder_output, num_classes=len(word_index_target)+1)

In [15]:
print('\nResult of One-Hot Encodded decoder_input sequencing: ')
print(decoder_input.shape)
print(data.target_input[0], decoder_input[0])


Result of One-Hot Encodded decoder_input sequencing: 
(1000, 19, 559)
	가.
 [[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [16]:
print('0-0\n', decoder_input[0][0])
print('0-1\n', decoder_input[0][1])
print('0-2\n', decoder_input[0][2])
print('0-18\n', decoder_input[0][18])

0-0
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

### to_categorical() & texts_to_matrix() 비교

In [17]:
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical

texts = ['우리 소망 꿈 통일']
tokenizer = Tokenizer(num_words=4)
tokenizer.fit_on_texts(texts)
word_index = tokenizer.word_index
data = tokenizer.texts_to_sequences(texts)
print('word_index: ', word_index)
print('data:', data)
print('to_categorical: ', to_categorical(data, num_classes=4))
print(tokenizer.texts_to_matrix(texts, mode='binary'))

word_index:  {'우리': 1, '소망': 2, '꿈': 3, '통일': 4}
data: [[1, 2, 3]]
to_categorical:  [[[0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]
[[0. 1. 1. 1.]]


In [18]:
print('decoder_input length:', len(decoder_input))
print('decoder_input type:', type(decoder_input))
print('decoder_input shape:', decoder_input.shape)

decoder_input length: 1000
decoder_input type: <class 'numpy.ndarray'>
decoder_input shape: (1000, 19, 559)


# 훈련용 Encoder

In [21]:
from keras.models import Model
from keras.layers import Input, LSTM, Dense

encoder_inputs = Input(shape=(None, len(word_index_source)+1))

encoder_lstm = LSTM(units=256, return_state=True)

encoder_outputs, state_h, state_c = encoder_lstm(encoder_inputs)
encoder_states = [state_h, state_c]

# 훈련용 Decoder

In [25]:
decoder_inputs = Input(shape=(None, len(word_index_target)+1))

decoder_lstm = LSTM(units=256, return_sequences=True, return_state=True)

decoder_outputs, _, _ = decoder_lstm(decoder_inputs, initial_state=encoder_states)

decoder_dense = Dense(len(word_index_target)+1, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

# 모델 훈련

In [ ]:
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

model.compile(optimizer='rmsprop', loss='categorical_crossentropy')
model.fit(x=[encoder_input, decoder_input], y=decoder_output, batch_size=64, epochs=1, validation_split=0.2)

Train on 800 samples, validate on 200 samples
Epoch 1/1


# 예측용 Encoder

In [1]:
encoder_model = Model(inputs=encoder_inputs, outputs=encoder_states)

NameError: name 'Model' is not defined

In [ ]:
decoder_state_input_h = Input(shape=(256,))
decoder_state_input_c = Input(shape=(256,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

decoder_outputs, state_h, state_c = decoder_lstm(decoder_inputs,
                                                 initial_state=decoder_states_inputs)

decoder_states = [state_h, state_c]
decoder_outputs = decoder_dense(decoder_outputs)

decoder_model = Model(inputs=[decoder_inputs] + decoder_states_inputs,
                      outputs=[decoder_outputs] + decoder_states)



In [ ]:
index_to_src = dict((i, char) for char, i in word_index_source.items())
index_to_tar = dict((i, char) for char, i in word_index_target.items())
print(index_to_tar)

# 예측함수

In [ ]:
def decode_sequence(input_seq):
    states_value = encoder_model.predict(input_seq)
    target_seq = np.zeros((1, 1, len(word_index_target)+1))
    target_seq[0, 0, word_index_target['\t']] = 1.
    stop_condition = False
    decoded_sentence = ""
    
    while not stop_condition:
        output_tokens, h, c = decoder_model.predict([target_seq] + states_value)
        sampled_token_index = np.argmax(output_tokens)
        
        if(sampled_token_index==0):
            sampled_token_index = 1
        
        sampled_char = index_to_tar[sampled_token_index]
        decoded_sentence += sampled_char
        
        if (sampled_char == '\n' or len(decoded_sentence) > max_tar_len):
            stop_condition = True
            
        target_seq = np.zeros((1, 1, len(word_index_target)+1))
        target_seq[0, 0, sampled_token_index] = 1.
        states_value = [h, c]
        
    return decoded_sentence

In [ ]:
import numpy as np

for seq_index in [1, 2, 3]:
    input_seq  = encoder_input[seq_index:seq_index+1]
    decoded_sentence = decode_sequence(input_seq)
    
    print('-'*35)
    print('입력 문장:', data.source[seq_index])
    print('정답 문장:', data.target[seq_index][1:len(data.target[seq_index])])
    print('번역기가 번역한 문장:', decoded_sentence[:len(decoded_sentence)-1])